server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

info:
  app:
    name: ${spring.application.name}


## GATEWAY CONFIGURATIONS
spring:
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        ## CANDIDATE SERVICE
        - id: candidate-service
          uri: lb://candidate-service
          predicates:
            - Path=/api/candidates/**
        ## COMMUNICATION SERVICE
        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/communications/**
        ## QUALIFICATION SERVICE
        - id: qualification-service
          uri: lb://qualification-service
          predicates:
            - Path=/api/qualifications/**
        ## JOB SERVICE
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**
        ## REGISTRY SERVER (EUREKA)
        - id: discovery-server-static
          uri: http://localhost:8081
          predicates:
            - Path=/eureka/**
#Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/spring-boot-microservices-realm
#Logging
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

