eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8081/eureka

#Security
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:18080/realms/spring-boot-microservices-realm