server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

info:
  app:
    name: ${spring.application.name}


## GATEWAY CONFIGURATIONS
spring:
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        ## CANDIDATE SERVICE
        - id: candidate-service
          uri: lb://candidate-service
          predicates:
            - Path=/candidates/**
        ## COMMUNICATION SERVICE
        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/communications/**
        ## QUALIFICATION SERVICE
        - id: qualification-service
          uri: lb://qualification-service
          predicates:
            - Path=/qualifications/**
        ## JOB SERVICE
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/jobs/**
        ## REGISTRY SERVER (EUREKA)
        - id: discovery-server-static
          uri: http://localhost:8081
          predicates:
            - Path=/eureka/**
#Security
keycloak:
  realm: kripton-talent-application
  auth-server-url: http://localhost:18080/auth
  resource: kripton-talent-client
  public-client: true
  bearer-only: true

#Logging
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

