server:
  port: 6001
kafkaServerUrl : "broker:9092"
uploadDirectory : "C:\\Users\\alaab\\OneDrive\\Desktop\\PFE-Files\\kripton-talent-front-new\\src\\assets\\images\\candidates"
matcher_parser_serverUrl : "http://matcher_parser:6000/"

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8081/eureka

spring:
  datasource:
    url: jdbc:mysql://database:3310/kripton-talent-db?useSSL=false
    username: root
    password: "root"




