kafkaServerUrl : "localhost:9092"
server:
  port: 6001
matcher_parser_serverUrl : "http://localhost:6000/"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}
##file input batch example
file:
  input: candidates.csv
###
uploadDirectory : "./uploads"
azure-account-name: "kriptonstorage"
azure-account-key: "H4azGiPlFSwhhNvZhLensPJC1rtlHcxVwy5lsb7GmgC05eELXxzP6IA3R4hN5GPt8qQRXgjIOViB+ASt3Rl3Yg=="
azure-endpoint: https://kriptonstorage.blob.core.windows.net/
spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/kripton-talent-db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
      ddl-auto: update

#Circuit Breaker config )
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
feign:
  circuitbreaker:
    enabled: 'true'

resilience4j:
  circuitbreaker:
    instances:
      breaker:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
  retry:
    instances:
      breaker:
        wait-duration: 5s
        max-attempts: '3'
  timelimiter:
    instances:
      breaker:
        timeout-duration: 3s


