server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8081/eureka

spring:
  datasource:
    url: jdbc:mysql://candidate_db:3310/candidate-service-db
    username: root
    password: 



