server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/candidate-service-db
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update

#Circuit Breaker config )
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
feign:
  circuitbreaker:
    enabled: 'true'

resilience4j:
  circuitbreaker:
    instances:
      breaker:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
  retry:
    instances:
      breaker:
        wait-duration: 5s
        max-attempts: '3'
  timelimiter:
    instances:
      breaker:
        timeout-duration: 3s

# Kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:kripton.candidateservice.kafka.CandidateAppliedEvent

