server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8081/eureka

spring:
  datasource:
    url: jdbc:mysql://candidate_db:3310/candidate-service-db?useSSL=false
    username: root
    password: "root"




