server:
  port: 6005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kripton.talent@gmail.com
    password: pjppthirtjcfgnwq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'