server:
  port: 8072

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: alaa.benfradj@esprit.tn
    password: csmgpyjsdskdtzuk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
