server:
  port: 8072

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

# Kafka Properties
spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: test
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring.json.type.mapping: event:kripton.communicationservice.kafka.CandidateAppliedEvent
