server:
  port: 6002

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8081/eureka

spring:
  datasource:
    url: jdbc:mysql://database:3320/kripton-talent-db
    username: root
    password: root
