server:
  port: 6002
kafkaServerUrl : "localhost:9092"
uploadDirectory : "C:\\Users\\alaab\\OneDrive\\Desktop\\PFE-Files\\kripton-talent-front-new\\src\\assets\\images\\jobs"
azure-account-name: "kriptonstorage"
azure-account-key: "H4azGiPlFSwhhNvZhLensPJC1rtlHcxVwy5lsb7GmgC05eELXxzP6IA3R4hN5GPt8qQRXgjIOViB+ASt3Rl3Yg=="
azure-endpoint: https://kriptonstorage.blob.core.windows.net/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/kripton-talent-db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

#Circuit Breaker config )
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
feign:
  circuitbreaker:
    enabled: 'true'

resilience4j:
  circuitbreaker:
    instances:
      breaker:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
  retry:
    instances:
      breaker:
        wait-duration: 5s
        max-attempts: '3'
  timelimiter:
    instances:
      breaker:
        timeout-duration: 3s
