server:
  port: 8071

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

#Tracing the requests
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: '1.0'