server:
  port: 8073

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/candidate-service-db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update