server:
  port: 6003

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8081/eureka

spring:
  datasource:
    url: jdbc:mysql://database:3310/kripton-talent-db?useSSL=false
    username: root
    password: root
