server:
  port: 8300

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8081/eureka

spring:
  datasource:
    url: jdbc:mysql://qualification_db:3330/qualification-service-db
    username: root
    password: root
