server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: localhost

#Tracing the requests
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: '1.0'